AST dump for ChapelContext after pass readExternC.
Module use list: 

{
  (314570 'import'(314567 call . Errors c"Error"))
  (314572 'use' OwnedObject)
  type Self[314609]
  {
    type contextReturnType[314613]
    function _unknown[42].enterContext[314579](arg _mt[314585]:_MT[201], arg this[314582] :
    Self) ref : _unknown[42] "ifc any return intent" "method" "no fn body"
    {
    }
    { scopeless type
      contextReturnType
    }
    function _unknown[42].exitContext[314591](arg _mt[314604]:_MT[201], arg this[314594] :
    Self, in arg error[314601] :
    (314598 call _owned(314600 'to nilable class from type' Error))) : _unknown[42] "method" "no fn body"
    {
    }
  }
  function chpl__verifyTypeContext[314617](arg x[314619]:_any[141](?)) : _unknown[42]
  {
    if(314657 call _cond_test(314651 call ==(314653 'implements interface' x contextManager) 2))
    {
      { scopeless
        (314623 call compilerWarning(314624 call +(314626 call :(314629 'typeof' x) string[244]) " is being used in a 'manage' statement ")(314634 call +(314636 call + "via its 'enterContext' and 'exitContext' methods. However, "(314641 call :(314644 'typeof' x) string[244])) " does not implement contextManager. ") "In the future, this will result in an error.")
      }
    }
  }
}